/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.adduser.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserInfo service. Represents a row in the &quot;PT_UserInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.adduser.model.impl.UserInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.adduser.model.impl.UserInfoImpl}.
 * </p>
 *
 * @author phantoan
 * @see UserInfo
 * @see com.liferay.adduser.model.impl.UserInfoImpl
 * @see com.liferay.adduser.model.impl.UserInfoModelImpl
 * @generated
 */
public interface UserInfoModel extends BaseModel<UserInfo>, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user info model instance should use the {@link UserInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this user info.
	 *
	 * @return the primary key of this user info
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this user info.
	 *
	 * @param primaryKey the primary key of this user info
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this user info.
	 *
	 * @return the uuid of this user info
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user info.
	 *
	 * @param uuid the uuid of this user info
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the group ID of this user info.
	 *
	 * @return the group ID of this user info
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user info.
	 *
	 * @param groupId the group ID of this user info
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user info.
	 *
	 * @return the company ID of this user info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user info.
	 *
	 * @param companyId the company ID of this user info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the creator ID of this user info.
	 *
	 * @return the creator ID of this user info
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this user info.
	 *
	 * @param creatorId the creator ID of this user info
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the create date of this user info.
	 *
	 * @return the create date of this user info
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user info.
	 *
	 * @param createDate the create date of this user info
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user info.
	 *
	 * @return the modified date of this user info
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user info.
	 *
	 * @param modifiedDate the modified date of this user info
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the user ID of this user info.
	 *
	 * @return the user ID of this user info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user info.
	 *
	 * @param userId the user ID of this user info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user info.
	 *
	 * @return the user uuid of this user info
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user info.
	 *
	 * @param userUuid the user uuid of this user info
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the code of this user info.
	 *
	 * @return the code of this user info
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this user info.
	 *
	 * @param code the code of this user info
	 */
	public void setCode(String code);

	/**
	 * Returns the username of this user info.
	 *
	 * @return the username of this user info
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this user info.
	 *
	 * @param username the username of this user info
	 */
	public void setUsername(String username);

	/**
	 * Returns the email of this user info.
	 *
	 * @return the email of this user info
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user info.
	 *
	 * @param email the email of this user info
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this user info.
	 *
	 * @return the phone of this user info
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this user info.
	 *
	 * @param phone the phone of this user info
	 */
	public void setPhone(String phone);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.adduser.model.UserInfo userInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.adduser.model.UserInfo> toCacheModel();

	@Override
	public com.liferay.adduser.model.UserInfo toEscapedModel();

	@Override
	public com.liferay.adduser.model.UserInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}